// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alpha/authzattrs/v1/authorization.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IssuerKeyType identifies the public-key algorithm used by an issuer.
type IssuerKeyType int32

const (
	IssuerKeyType_ISSUER_KEY_TYPE_UNSPECIFIED IssuerKeyType = 0
	IssuerKeyType_ISSUER_KEY_TYPE_ED25519     IssuerKeyType = 1
)

var IssuerKeyType_name = map[int32]string{
	0: "ISSUER_KEY_TYPE_UNSPECIFIED",
	1: "ISSUER_KEY_TYPE_ED25519",
}

var IssuerKeyType_value = map[string]int32{
	"ISSUER_KEY_TYPE_UNSPECIFIED": 0,
	"ISSUER_KEY_TYPE_ED25519":     1,
}

func (x IssuerKeyType) String() string {
	return proto.EnumName(IssuerKeyType_name, int32(x))
}

func (IssuerKeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{0}
}

// BankSendConstraints defines the public typed constraints for a V1 MsgSend.
type BankSendConstraints struct {
	Denom     string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Receiver  string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	MaxAmount string `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
}

func (m *BankSendConstraints) Reset()         { *m = BankSendConstraints{} }
func (m *BankSendConstraints) String() string { return proto.CompactTextString(m) }
func (*BankSendConstraints) ProtoMessage()    {}
func (*BankSendConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{0}
}
func (m *BankSendConstraints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BankSendConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BankSendConstraints.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BankSendConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankSendConstraints.Merge(m, src)
}
func (m *BankSendConstraints) XXX_Size() int {
	return m.Size()
}
func (m *BankSendConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_BankSendConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_BankSendConstraints proto.InternalMessageInfo

func (m *BankSendConstraints) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *BankSendConstraints) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *BankSendConstraints) GetMaxAmount() string {
	if m != nil {
		return m.MaxAmount
	}
	return ""
}

// AuthorizationRecord is the current committed authorization for one logical key.
type AuthorizationRecord struct {
	AuthorizationId     string              `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	Subject             string              `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	MsgTypeUrl          string              `protobuf:"bytes,3,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	PolicyId            string              `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion       uint64              `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	IssuerSetId         uint64              `protobuf:"varint,6,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	ValidFromHeight     int64               `protobuf:"varint,7,opt,name=valid_from_height,json=validFromHeight,proto3" json:"valid_from_height,omitempty"`
	ValidUntilHeight    int64               `protobuf:"varint,8,opt,name=valid_until_height,json=validUntilHeight,proto3" json:"valid_until_height,omitempty"`
	Revoked             bool                `protobuf:"varint,9,opt,name=revoked,proto3" json:"revoked,omitempty"`
	BankSendConstraints BankSendConstraints `protobuf:"bytes,10,opt,name=bank_send_constraints,json=bankSendConstraints,proto3" json:"bank_send_constraints"`
}

func (m *AuthorizationRecord) Reset()         { *m = AuthorizationRecord{} }
func (m *AuthorizationRecord) String() string { return proto.CompactTextString(m) }
func (*AuthorizationRecord) ProtoMessage()    {}
func (*AuthorizationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{1}
}
func (m *AuthorizationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationRecord.Merge(m, src)
}
func (m *AuthorizationRecord) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationRecord proto.InternalMessageInfo

func (m *AuthorizationRecord) GetAuthorizationId() string {
	if m != nil {
		return m.AuthorizationId
	}
	return ""
}

func (m *AuthorizationRecord) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthorizationRecord) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *AuthorizationRecord) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *AuthorizationRecord) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *AuthorizationRecord) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *AuthorizationRecord) GetValidFromHeight() int64 {
	if m != nil {
		return m.ValidFromHeight
	}
	return 0
}

func (m *AuthorizationRecord) GetValidUntilHeight() int64 {
	if m != nil {
		return m.ValidUntilHeight
	}
	return 0
}

func (m *AuthorizationRecord) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *AuthorizationRecord) GetBankSendConstraints() BankSendConstraints {
	if m != nil {
		return m.BankSendConstraints
	}
	return BankSendConstraints{}
}

// AuthorizationBatchSignDoc is the canonical payload signed by issuers.
type AuthorizationBatchSignDoc struct {
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BatchId       uint64                 `protobuf:"varint,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion uint64                 `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyHash    []byte                 `protobuf:"bytes,6,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	IssuerSetId   uint64                 `protobuf:"varint,7,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	Records       []*AuthorizationRecord `protobuf:"bytes,8,rep,name=records,proto3" json:"records,omitempty"`
}

func (m *AuthorizationBatchSignDoc) Reset()         { *m = AuthorizationBatchSignDoc{} }
func (m *AuthorizationBatchSignDoc) String() string { return proto.CompactTextString(m) }
func (*AuthorizationBatchSignDoc) ProtoMessage()    {}
func (*AuthorizationBatchSignDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{2}
}
func (m *AuthorizationBatchSignDoc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationBatchSignDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationBatchSignDoc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationBatchSignDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationBatchSignDoc.Merge(m, src)
}
func (m *AuthorizationBatchSignDoc) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationBatchSignDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationBatchSignDoc.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationBatchSignDoc proto.InternalMessageInfo

func (m *AuthorizationBatchSignDoc) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AuthorizationBatchSignDoc) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *AuthorizationBatchSignDoc) GetBatchId() uint64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *AuthorizationBatchSignDoc) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *AuthorizationBatchSignDoc) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *AuthorizationBatchSignDoc) GetPolicyHash() []byte {
	if m != nil {
		return m.PolicyHash
	}
	return nil
}

func (m *AuthorizationBatchSignDoc) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *AuthorizationBatchSignDoc) GetRecords() []*AuthorizationRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// BatchSignature is one issuer signature over canonical sign bytes.
type BatchSignature struct {
	IssuerId  string `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *BatchSignature) Reset()         { *m = BatchSignature{} }
func (m *BatchSignature) String() string { return proto.CompactTextString(m) }
func (*BatchSignature) ProtoMessage()    {}
func (*BatchSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{3}
}
func (m *BatchSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSignature.Merge(m, src)
}
func (m *BatchSignature) XXX_Size() int {
	return m.Size()
}
func (m *BatchSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSignature.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSignature proto.InternalMessageInfo

func (m *BatchSignature) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *BatchSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// AuthorizationBatch carries a sign document and its issuer signatures.
type AuthorizationBatch struct {
	SignDoc    *AuthorizationBatchSignDoc `protobuf:"bytes,1,opt,name=sign_doc,json=signDoc,proto3" json:"sign_doc,omitempty"`
	Signatures []*BatchSignature          `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *AuthorizationBatch) Reset()         { *m = AuthorizationBatch{} }
func (m *AuthorizationBatch) String() string { return proto.CompactTextString(m) }
func (*AuthorizationBatch) ProtoMessage()    {}
func (*AuthorizationBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{4}
}
func (m *AuthorizationBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationBatch.Merge(m, src)
}
func (m *AuthorizationBatch) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationBatch.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationBatch proto.InternalMessageInfo

func (m *AuthorizationBatch) GetSignDoc() *AuthorizationBatchSignDoc {
	if m != nil {
		return m.SignDoc
	}
	return nil
}

func (m *AuthorizationBatch) GetSignatures() []*BatchSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// IssuerSet defines one weighted issuer trust set for a policy and message type.
type IssuerSet struct {
	IssuerSetId     uint64 `protobuf:"varint,1,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	Active          bool   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	PolicyId        string `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	MsgTypeUrl      string `protobuf:"bytes,4,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	ThresholdWeight uint64 `protobuf:"varint,5,opt,name=threshold_weight,json=thresholdWeight,proto3" json:"threshold_weight,omitempty"`
}

func (m *IssuerSet) Reset()         { *m = IssuerSet{} }
func (m *IssuerSet) String() string { return proto.CompactTextString(m) }
func (*IssuerSet) ProtoMessage()    {}
func (*IssuerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{5}
}
func (m *IssuerSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IssuerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IssuerSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IssuerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuerSet.Merge(m, src)
}
func (m *IssuerSet) XXX_Size() int {
	return m.Size()
}
func (m *IssuerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuerSet.DiscardUnknown(m)
}

var xxx_messageInfo_IssuerSet proto.InternalMessageInfo

func (m *IssuerSet) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *IssuerSet) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *IssuerSet) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *IssuerSet) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *IssuerSet) GetThresholdWeight() uint64 {
	if m != nil {
		return m.ThresholdWeight
	}
	return 0
}

// Issuer defines one issuer scoped to an issuer set.
type Issuer struct {
	IssuerSetId      uint64        `protobuf:"varint,1,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	IssuerId         string        `protobuf:"bytes,2,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	KeyType          IssuerKeyType `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=alpha.authzattrs.v1.IssuerKeyType" json:"key_type,omitempty"`
	PublicKey        []byte        `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Weight           uint64        `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Active           bool          `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	ValidFromHeight  int64         `protobuf:"varint,7,opt,name=valid_from_height,json=validFromHeight,proto3" json:"valid_from_height,omitempty"`
	ValidUntilHeight int64         `protobuf:"varint,8,opt,name=valid_until_height,json=validUntilHeight,proto3" json:"valid_until_height,omitempty"`
}

func (m *Issuer) Reset()         { *m = Issuer{} }
func (m *Issuer) String() string { return proto.CompactTextString(m) }
func (*Issuer) ProtoMessage()    {}
func (*Issuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{6}
}
func (m *Issuer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Issuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Issuer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Issuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issuer.Merge(m, src)
}
func (m *Issuer) XXX_Size() int {
	return m.Size()
}
func (m *Issuer) XXX_DiscardUnknown() {
	xxx_messageInfo_Issuer.DiscardUnknown(m)
}

var xxx_messageInfo_Issuer proto.InternalMessageInfo

func (m *Issuer) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *Issuer) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *Issuer) GetKeyType() IssuerKeyType {
	if m != nil {
		return m.KeyType
	}
	return IssuerKeyType_ISSUER_KEY_TYPE_UNSPECIFIED
}

func (m *Issuer) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Issuer) GetWeight() uint64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Issuer) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Issuer) GetValidFromHeight() int64 {
	if m != nil {
		return m.ValidFromHeight
	}
	return 0
}

func (m *Issuer) GetValidUntilHeight() int64 {
	if m != nil {
		return m.ValidUntilHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("alpha.authzattrs.v1.IssuerKeyType", IssuerKeyType_name, IssuerKeyType_value)
	proto.RegisterType((*BankSendConstraints)(nil), "alpha.authzattrs.v1.BankSendConstraints")
	proto.RegisterType((*AuthorizationRecord)(nil), "alpha.authzattrs.v1.AuthorizationRecord")
	proto.RegisterType((*AuthorizationBatchSignDoc)(nil), "alpha.authzattrs.v1.AuthorizationBatchSignDoc")
	proto.RegisterType((*BatchSignature)(nil), "alpha.authzattrs.v1.BatchSignature")
	proto.RegisterType((*AuthorizationBatch)(nil), "alpha.authzattrs.v1.AuthorizationBatch")
	proto.RegisterType((*IssuerSet)(nil), "alpha.authzattrs.v1.IssuerSet")
	proto.RegisterType((*Issuer)(nil), "alpha.authzattrs.v1.Issuer")
}

func init() {
	proto.RegisterFile("alpha/authzattrs/v1/authorization.proto", fileDescriptor_ca609f79184793ea)
}

var fileDescriptor_ca609f79184793ea = []byte{
	// 838 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xda, 0xae, 0xbd, 0x7e, 0xf9, 0x67, 0x26, 0xa5, 0x6c, 0x1b, 0x70, 0xac, 0x20, 0x84,
	0x5b, 0x21, 0x47, 0x31, 0xea, 0x01, 0x24, 0x0e, 0x75, 0xe2, 0xaa, 0xab, 0x08, 0x54, 0xd6, 0x0d,
	0xa8, 0x5c, 0x56, 0xe3, 0x9d, 0xc1, 0x3b, 0x78, 0x77, 0xc7, 0x9a, 0x19, 0x9b, 0xb8, 0x9f, 0x82,
	0x8f, 0xc0, 0x99, 0x2f, 0xc0, 0x85, 0x13, 0xa7, 0x1e, 0x7b, 0xe4, 0x84, 0x50, 0x72, 0xe1, 0x63,
	0xa0, 0x9d, 0x19, 0x3b, 0x76, 0x9c, 0x08, 0x0e, 0xf4, 0xe6, 0xf7, 0x7b, 0xbf, 0x7d, 0xf3, 0xde,
	0xef, 0xf7, 0x3c, 0x03, 0x1f, 0xe3, 0x64, 0x1c, 0xe3, 0x43, 0x3c, 0x51, 0xf1, 0x2b, 0xac, 0x94,
	0x90, 0x87, 0xd3, 0x23, 0x1d, 0x71, 0xc1, 0x5e, 0x61, 0xc5, 0x78, 0xd6, 0x1e, 0x0b, 0xae, 0x38,
	0xda, 0xd5, 0xc4, 0xf6, 0x15, 0xb1, 0x3d, 0x3d, 0x7a, 0x70, 0x77, 0xc8, 0x87, 0x5c, 0xe7, 0x0f,
	0xf3, 0x5f, 0x86, 0x7a, 0x90, 0xc0, 0x6e, 0x17, 0x67, 0xa3, 0x3e, 0xcd, 0xc8, 0x31, 0xcf, 0xa4,
	0x12, 0x98, 0x65, 0x4a, 0xa2, 0xbb, 0x70, 0x87, 0xd0, 0x8c, 0xa7, 0x9e, 0xd3, 0x74, 0x5a, 0xb5,
	0xc0, 0x04, 0xe8, 0x01, 0xb8, 0x82, 0x46, 0x94, 0x4d, 0xa9, 0xf0, 0x8a, 0x3a, 0xb1, 0x88, 0xd1,
	0x07, 0x00, 0x29, 0x3e, 0x0f, 0x71, 0xca, 0x27, 0x99, 0xf2, 0x4a, 0x3a, 0x5b, 0x4b, 0xf1, 0xf9,
	0x13, 0x0d, 0x7c, 0x5e, 0xfe, 0xfb, 0xe7, 0x7d, 0xe7, 0xe0, 0xf7, 0x12, 0xec, 0x3e, 0x59, 0x6e,
	0x38, 0xa0, 0x11, 0x17, 0x04, 0x3d, 0x84, 0xfa, 0xca, 0x1c, 0x21, 0x23, 0xf6, 0xe4, 0x9d, 0x15,
	0xdc, 0x27, 0xc8, 0x83, 0xaa, 0x9c, 0x0c, 0x7e, 0xa0, 0x91, 0xb2, 0x2d, 0xcc, 0x43, 0xd4, 0x84,
	0xcd, 0x54, 0x0e, 0x43, 0x35, 0x1b, 0xd3, 0x70, 0x22, 0x12, 0xdb, 0x03, 0xa4, 0x72, 0xf8, 0x62,
	0x36, 0xa6, 0x67, 0x22, 0x41, 0x7b, 0x50, 0x1b, 0xf3, 0x84, 0x45, 0xb3, 0xbc, 0x7e, 0xd9, 0x0c,
	0x60, 0x00, 0x9f, 0xa0, 0x8f, 0x60, 0xdb, 0x26, 0xa7, 0x54, 0x48, 0xc6, 0x33, 0xef, 0x4e, 0xd3,
	0x69, 0x95, 0x83, 0x2d, 0x83, 0x7e, 0x63, 0x40, 0x74, 0x00, 0x5b, 0x4c, 0xca, 0x09, 0x15, 0xa1,
	0xa4, 0x2a, 0xaf, 0x53, 0xd1, 0xac, 0x0d, 0x03, 0xf6, 0xa9, 0xf2, 0x09, 0x7a, 0x04, 0xef, 0x4c,
	0x71, 0xc2, 0x48, 0xf8, 0xbd, 0xe0, 0x69, 0x18, 0x53, 0x36, 0x8c, 0x95, 0x57, 0x6d, 0x3a, 0xad,
	0x52, 0xb0, 0xa3, 0x13, 0x4f, 0x05, 0x4f, 0x9f, 0x69, 0x18, 0x7d, 0x02, 0xc8, 0x70, 0x27, 0x99,
	0x62, 0xc9, 0x9c, 0xec, 0x6a, 0x72, 0x5d, 0x67, 0xce, 0xf2, 0x84, 0x65, 0x7b, 0x50, 0x15, 0x74,
	0xca, 0x47, 0x94, 0x78, 0xb5, 0xa6, 0xd3, 0x72, 0x83, 0x79, 0x88, 0x06, 0xf0, 0xee, 0x00, 0x67,
	0xa3, 0x50, 0xd2, 0x8c, 0x84, 0xd1, 0x95, 0x95, 0x1e, 0x34, 0x9d, 0xd6, 0x46, 0xa7, 0xd5, 0xbe,
	0x61, 0x27, 0xda, 0x37, 0x58, 0xdf, 0x2d, 0xbf, 0xfe, 0x73, 0xbf, 0x10, 0xec, 0x0e, 0xd6, 0x53,
	0xd6, 0xc4, 0xdf, 0x8a, 0x70, 0x7f, 0xc5, 0xc4, 0x2e, 0x56, 0x51, 0xdc, 0x67, 0xc3, 0xec, 0x84,
	0x47, 0xe8, 0x1e, 0x54, 0x08, 0x4f, 0x31, 0xcb, 0xac, 0x81, 0x36, 0x42, 0xf7, 0xc1, 0x8d, 0x62,
	0xcc, 0xb4, 0xb5, 0xd6, 0x38, 0x1d, 0xfb, 0x24, 0x4f, 0x0d, 0xf2, 0x12, 0x79, 0xaa, 0xa4, 0xd5,
	0xac, 0xea, 0xd8, 0x27, 0xff, 0x8b, 0x63, 0xfb, 0xb0, 0x61, 0x69, 0x31, 0x96, 0xb1, 0xf6, 0x6b,
	0x33, 0x00, 0x03, 0x3d, 0xc3, 0x32, 0x5e, 0xb7, 0xb4, 0xba, 0x6e, 0x69, 0x37, 0x17, 0x3e, 0xdf,
	0x55, 0xe9, 0xb9, 0xcd, 0xd2, 0xad, 0x82, 0xde, 0xb0, 0xdc, 0xc1, 0xfc, 0x43, 0x2b, 0xdf, 0xd7,
	0xb0, 0xbd, 0x10, 0x0c, 0xab, 0x89, 0xa0, 0xf9, 0x90, 0xf6, 0xfc, 0xc5, 0xda, 0xbb, 0x06, 0xf0,
	0x09, 0x7a, 0x1f, 0x6a, 0x72, 0xce, 0xd4, 0xc2, 0x6d, 0x06, 0x57, 0x80, 0x2d, 0xf9, 0x8b, 0x03,
	0x68, 0xdd, 0x11, 0xe4, 0x83, 0x9b, 0x33, 0x43, 0xc2, 0x23, 0x5d, 0x76, 0xa3, 0xd3, 0xfe, 0xf7,
	0xa6, 0x97, 0xcd, 0x0c, 0xaa, 0xd2, 0xba, 0x7a, 0x0c, 0xb0, 0x38, 0x54, 0x7a, 0x45, 0xad, 0xc0,
	0x87, 0xb7, 0xac, 0xd4, 0xf2, 0x6c, 0xc1, 0xd2, 0x67, 0xb6, 0xd9, 0x5f, 0x1d, 0xa8, 0xf9, 0x73,
	0x65, 0xd7, 0xb5, 0x77, 0xd6, 0xb5, 0xbf, 0x07, 0x15, 0x1c, 0x29, 0x36, 0x35, 0xf3, 0xbb, 0x81,
	0x8d, 0x56, 0x97, 0xa3, 0x74, 0x6d, 0x39, 0xae, 0xdf, 0x06, 0xe5, 0xb5, 0xdb, 0xe0, 0x21, 0xd4,
	0x55, 0x2c, 0xa8, 0x8c, 0x79, 0x42, 0xc2, 0x1f, 0xcd, 0xff, 0xce, 0x2c, 0xd0, 0xce, 0x02, 0xff,
	0x56, 0xc3, 0xf3, 0xce, 0x8b, 0x50, 0x31, 0x9d, 0xff, 0xa7, 0xb6, 0x57, 0x6c, 0x2d, 0x5e, 0xb3,
	0xf5, 0x0b, 0x70, 0x47, 0x74, 0xa6, 0xdb, 0xd3, 0xad, 0x6f, 0x77, 0x0e, 0x6e, 0x94, 0xd3, 0x9c,
	0x77, 0x4a, 0x67, 0x79, 0xd7, 0x41, 0x75, 0x64, 0x7e, 0xe4, 0xb7, 0xed, 0x78, 0x32, 0x48, 0x58,
	0x14, 0x8e, 0xe8, 0x4c, 0xcf, 0xb6, 0x19, 0xd4, 0x0c, 0x72, 0x4a, 0x67, 0xb9, 0x62, 0x2b, 0x03,
	0xd9, 0x68, 0x49, 0xc9, 0xca, 0x8a, 0x92, 0x6f, 0xed, 0xc2, 0x32, 0xca, 0x3d, 0xfa, 0x12, 0xb6,
	0x56, 0x06, 0x41, 0xfb, 0xb0, 0xe7, 0xf7, 0xfb, 0x67, 0xbd, 0x20, 0x3c, 0xed, 0xbd, 0x0c, 0x5f,
	0xbc, 0x7c, 0xde, 0x0b, 0xcf, 0xbe, 0xea, 0x3f, 0xef, 0x1d, 0xfb, 0x4f, 0xfd, 0xde, 0x49, 0xbd,
	0x80, 0xf6, 0xe0, 0xbd, 0xeb, 0x84, 0xde, 0x49, 0xe7, 0xf1, 0xe3, 0xa3, 0xcf, 0xea, 0x4e, 0xb7,
	0xf3, 0xfa, 0xa2, 0xe1, 0xbc, 0xb9, 0x68, 0x38, 0x7f, 0x5d, 0x34, 0x9c, 0x9f, 0x2e, 0x1b, 0x85,
	0x37, 0x97, 0x8d, 0xc2, 0x1f, 0x97, 0x8d, 0xc2, 0x77, 0x9e, 0x79, 0x22, 0xcf, 0x97, 0x1f, 0xc9,
	0x5c, 0x63, 0x39, 0xa8, 0xe8, 0xf7, 0xee, 0xd3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x1b,
	0xde, 0x32, 0x45, 0x07, 0x00, 0x00,
}

func (this *BankSendConstraints) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BankSendConstraints)
	if !ok {
		that2, ok := that.(BankSendConstraints)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.Receiver != that1.Receiver {
		return false
	}
	if this.MaxAmount != that1.MaxAmount {
		return false
	}
	return true
}
func (this *AuthorizationRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AuthorizationRecord)
	if !ok {
		that2, ok := that.(AuthorizationRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AuthorizationId != that1.AuthorizationId {
		return false
	}
	if this.Subject != that1.Subject {
		return false
	}
	if this.MsgTypeUrl != that1.MsgTypeUrl {
		return false
	}
	if this.PolicyId != that1.PolicyId {
		return false
	}
	if this.PolicyVersion != that1.PolicyVersion {
		return false
	}
	if this.IssuerSetId != that1.IssuerSetId {
		return false
	}
	if this.ValidFromHeight != that1.ValidFromHeight {
		return false
	}
	if this.ValidUntilHeight != that1.ValidUntilHeight {
		return false
	}
	if this.Revoked != that1.Revoked {
		return false
	}
	if !this.BankSendConstraints.Equal(&that1.BankSendConstraints) {
		return false
	}
	return true
}
func (this *AuthorizationBatchSignDoc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AuthorizationBatchSignDoc)
	if !ok {
		that2, ok := that.(AuthorizationBatchSignDoc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if this.ChainId != that1.ChainId {
		return false
	}
	if this.BatchId != that1.BatchId {
		return false
	}
	if this.PolicyId != that1.PolicyId {
		return false
	}
	if this.PolicyVersion != that1.PolicyVersion {
		return false
	}
	if !bytes.Equal(this.PolicyHash, that1.PolicyHash) {
		return false
	}
	if this.IssuerSetId != that1.IssuerSetId {
		return false
	}
	if len(this.Records) != len(that1.Records) {
		return false
	}
	for i := range this.Records {
		if !this.Records[i].Equal(that1.Records[i]) {
			return false
		}
	}
	return true
}
func (this *BatchSignature) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BatchSignature)
	if !ok {
		that2, ok := that.(BatchSignature)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IssuerId != that1.IssuerId {
		return false
	}
	if !bytes.Equal(this.Signature, that1.Signature) {
		return false
	}
	return true
}
func (this *AuthorizationBatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AuthorizationBatch)
	if !ok {
		that2, ok := that.(AuthorizationBatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.SignDoc.Equal(that1.SignDoc) {
		return false
	}
	if len(this.Signatures) != len(that1.Signatures) {
		return false
	}
	for i := range this.Signatures {
		if !this.Signatures[i].Equal(that1.Signatures[i]) {
			return false
		}
	}
	return true
}
func (this *IssuerSet) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IssuerSet)
	if !ok {
		that2, ok := that.(IssuerSet)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IssuerSetId != that1.IssuerSetId {
		return false
	}
	if this.Active != that1.Active {
		return false
	}
	if this.PolicyId != that1.PolicyId {
		return false
	}
	if this.MsgTypeUrl != that1.MsgTypeUrl {
		return false
	}
	if this.ThresholdWeight != that1.ThresholdWeight {
		return false
	}
	return true
}
func (this *Issuer) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Issuer)
	if !ok {
		that2, ok := that.(Issuer)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IssuerSetId != that1.IssuerSetId {
		return false
	}
	if this.IssuerId != that1.IssuerId {
		return false
	}
	if this.KeyType != that1.KeyType {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if this.Weight != that1.Weight {
		return false
	}
	if this.Active != that1.Active {
		return false
	}
	if this.ValidFromHeight != that1.ValidFromHeight {
		return false
	}
	if this.ValidUntilHeight != that1.ValidUntilHeight {
		return false
	}
	return true
}
func (m *BankSendConstraints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BankSendConstraints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BankSendConstraints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxAmount) > 0 {
		i -= len(m.MaxAmount)
		copy(dAtA[i:], m.MaxAmount)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.MaxAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BankSendConstraints.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthorization(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.Revoked {
		i--
		if m.Revoked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.ValidUntilHeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ValidUntilHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.ValidFromHeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ValidFromHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x30
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuthorizationId) > 0 {
		i -= len(m.AuthorizationId)
		copy(dAtA[i:], m.AuthorizationId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.AuthorizationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationBatchSignDoc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationBatchSignDoc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationBatchSignDoc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Records) > 0 {
		for iNdEx := len(m.Records) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Records[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthorization(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x38
	}
	if len(m.PolicyHash) > 0 {
		i -= len(m.PolicyHash)
		copy(dAtA[i:], m.PolicyHash)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.PolicyHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x22
	}
	if m.BatchId != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.BatchId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IssuerId) > 0 {
		i -= len(m.IssuerId)
		copy(dAtA[i:], m.IssuerId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.IssuerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthorization(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.SignDoc != nil {
		{
			size, err := m.SignDoc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthorization(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IssuerSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IssuerSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IssuerSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ThresholdWeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ThresholdWeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Issuer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Issuer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Issuer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidUntilHeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ValidUntilHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.ValidFromHeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ValidFromHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Weight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.KeyType != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.KeyType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.IssuerId) > 0 {
		i -= len(m.IssuerId)
		copy(dAtA[i:], m.IssuerId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.IssuerId)))
		i--
		dAtA[i] = 0x12
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthorization(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthorization(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BankSendConstraints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.MaxAmount)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	return n
}

func (m *AuthorizationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuthorizationId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovAuthorization(uint64(m.PolicyVersion))
	}
	if m.IssuerSetId != 0 {
		n += 1 + sovAuthorization(uint64(m.IssuerSetId))
	}
	if m.ValidFromHeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ValidFromHeight))
	}
	if m.ValidUntilHeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ValidUntilHeight))
	}
	if m.Revoked {
		n += 2
	}
	l = m.BankSendConstraints.Size()
	n += 1 + l + sovAuthorization(uint64(l))
	return n
}

func (m *AuthorizationBatchSignDoc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.BatchId != 0 {
		n += 1 + sovAuthorization(uint64(m.BatchId))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovAuthorization(uint64(m.PolicyVersion))
	}
	l = len(m.PolicyHash)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.IssuerSetId != 0 {
		n += 1 + sovAuthorization(uint64(m.IssuerSetId))
	}
	if len(m.Records) > 0 {
		for _, e := range m.Records {
			l = e.Size()
			n += 1 + l + sovAuthorization(uint64(l))
		}
	}
	return n
}

func (m *BatchSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IssuerId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	return n
}

func (m *AuthorizationBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SignDoc != nil {
		l = m.SignDoc.Size()
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovAuthorization(uint64(l))
		}
	}
	return n
}

func (m *IssuerSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IssuerSetId != 0 {
		n += 1 + sovAuthorization(uint64(m.IssuerSetId))
	}
	if m.Active {
		n += 2
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.ThresholdWeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ThresholdWeight))
	}
	return n
}

func (m *Issuer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IssuerSetId != 0 {
		n += 1 + sovAuthorization(uint64(m.IssuerSetId))
	}
	l = len(m.IssuerId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.KeyType != 0 {
		n += 1 + sovAuthorization(uint64(m.KeyType))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovAuthorization(uint64(m.Weight))
	}
	if m.Active {
		n += 2
	}
	if m.ValidFromHeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ValidFromHeight))
	}
	if m.ValidUntilHeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ValidUntilHeight))
	}
	return n
}

func sovAuthorization(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthorization(x uint64) (n int) {
	return sovAuthorization(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BankSendConstraints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BankSendConstraints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BankSendConstraints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidFromHeight", wireType)
			}
			m.ValidFromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidFromHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilHeight", wireType)
			}
			m.ValidUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Revoked = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BankSendConstraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BankSendConstraints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationBatchSignDoc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationBatchSignDoc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationBatchSignDoc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			m.BatchId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyHash = append(m.PolicyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PolicyHash == nil {
				m.PolicyHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Records", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Records = append(m.Records, &AuthorizationRecord{})
			if err := m.Records[len(m.Records)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignDoc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SignDoc == nil {
				m.SignDoc = &AuthorizationBatchSignDoc{}
			}
			if err := m.SignDoc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, &BatchSignature{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IssuerSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IssuerSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IssuerSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThresholdWeight", wireType)
			}
			m.ThresholdWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ThresholdWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Issuer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Issuer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Issuer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyType", wireType)
			}
			m.KeyType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyType |= IssuerKeyType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidFromHeight", wireType)
			}
			m.ValidFromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidFromHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilHeight", wireType)
			}
			m.ValidUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthorization(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthorization
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthorization
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthorization
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthorization        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthorization          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthorization = fmt.Errorf("proto: unexpected end of group")
)
