// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alpha/authzattrs/v1/authorization.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BankSendConstraints defines the public typed constraints for a V1 MsgSend.
type BankSendConstraints struct {
	Denom     string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Receiver  string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	MaxAmount string `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
}

func (m *BankSendConstraints) Reset()         { *m = BankSendConstraints{} }
func (m *BankSendConstraints) String() string { return proto.CompactTextString(m) }
func (*BankSendConstraints) ProtoMessage()    {}
func (*BankSendConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{0}
}
func (m *BankSendConstraints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BankSendConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BankSendConstraints.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BankSendConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankSendConstraints.Merge(m, src)
}
func (m *BankSendConstraints) XXX_Size() int {
	return m.Size()
}
func (m *BankSendConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_BankSendConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_BankSendConstraints proto.InternalMessageInfo

func (m *BankSendConstraints) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *BankSendConstraints) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *BankSendConstraints) GetMaxAmount() string {
	if m != nil {
		return m.MaxAmount
	}
	return ""
}

// AuthorizationRecord is the current committed authorization for one logical key.
type AuthorizationRecord struct {
	AuthorizationId     string              `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	Subject             string              `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	MsgTypeUrl          string              `protobuf:"bytes,3,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	PolicyId            string              `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion       uint64              `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	IssuerSetId         uint64              `protobuf:"varint,6,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	ValidFromHeight     int64               `protobuf:"varint,7,opt,name=valid_from_height,json=validFromHeight,proto3" json:"valid_from_height,omitempty"`
	ValidUntilHeight    int64               `protobuf:"varint,8,opt,name=valid_until_height,json=validUntilHeight,proto3" json:"valid_until_height,omitempty"`
	Revoked             bool                `protobuf:"varint,9,opt,name=revoked,proto3" json:"revoked,omitempty"`
	BankSendConstraints BankSendConstraints `protobuf:"bytes,10,opt,name=bank_send_constraints,json=bankSendConstraints,proto3" json:"bank_send_constraints"`
}

func (m *AuthorizationRecord) Reset()         { *m = AuthorizationRecord{} }
func (m *AuthorizationRecord) String() string { return proto.CompactTextString(m) }
func (*AuthorizationRecord) ProtoMessage()    {}
func (*AuthorizationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca609f79184793ea, []int{1}
}
func (m *AuthorizationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationRecord.Merge(m, src)
}
func (m *AuthorizationRecord) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationRecord proto.InternalMessageInfo

func (m *AuthorizationRecord) GetAuthorizationId() string {
	if m != nil {
		return m.AuthorizationId
	}
	return ""
}

func (m *AuthorizationRecord) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthorizationRecord) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *AuthorizationRecord) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *AuthorizationRecord) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *AuthorizationRecord) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *AuthorizationRecord) GetValidFromHeight() int64 {
	if m != nil {
		return m.ValidFromHeight
	}
	return 0
}

func (m *AuthorizationRecord) GetValidUntilHeight() int64 {
	if m != nil {
		return m.ValidUntilHeight
	}
	return 0
}

func (m *AuthorizationRecord) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *AuthorizationRecord) GetBankSendConstraints() BankSendConstraints {
	if m != nil {
		return m.BankSendConstraints
	}
	return BankSendConstraints{}
}

func init() {
	proto.RegisterType((*BankSendConstraints)(nil), "alpha.authzattrs.v1.BankSendConstraints")
	proto.RegisterType((*AuthorizationRecord)(nil), "alpha.authzattrs.v1.AuthorizationRecord")
}

func init() {
	proto.RegisterFile("alpha/authzattrs/v1/authorization.proto", fileDescriptor_ca609f79184793ea)
}

var fileDescriptor_ca609f79184793ea = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x6b, 0xd6, 0xad, 0xad, 0xc7, 0xd8, 0x70, 0x87, 0x64, 0x0d, 0x91, 0x45, 0x95, 0x10,
	0x01, 0xa1, 0x54, 0x1b, 0x37, 0x6e, 0x2b, 0x12, 0xa2, 0xd7, 0x8c, 0x71, 0xe0, 0x12, 0x39, 0xb1,
	0x49, 0x4d, 0x13, 0x3b, 0xb2, 0x9d, 0xa8, 0xdd, 0x53, 0xf0, 0x08, 0x3c, 0x0b, 0xa7, 0x1d, 0x77,
	0xe4, 0x84, 0x50, 0x7b, 0xe1, 0x31, 0x50, 0xec, 0x94, 0x6d, 0x62, 0xb7, 0x7c, 0xdf, 0xf7, 0x93,
	0xf3, 0xff, 0xeb, 0xff, 0xc1, 0x17, 0x24, 0x2f, 0x67, 0x64, 0x4c, 0x2a, 0x33, 0xbb, 0x24, 0xc6,
	0x28, 0x3d, 0xae, 0x4f, 0xac, 0x92, 0x8a, 0x5f, 0x12, 0xc3, 0xa5, 0x08, 0x4b, 0x25, 0x8d, 0x44,
	0x43, 0x0b, 0x86, 0x37, 0x60, 0x58, 0x9f, 0x1c, 0x1d, 0x66, 0x32, 0x93, 0x36, 0x1f, 0x37, 0x5f,
	0x0e, 0x1d, 0xe5, 0x70, 0x38, 0x21, 0x62, 0x7e, 0xce, 0x04, 0x7d, 0x27, 0x85, 0x36, 0x8a, 0x70,
	0x61, 0x34, 0x3a, 0x84, 0xdb, 0x94, 0x09, 0x59, 0x60, 0xe0, 0x83, 0x60, 0x10, 0x39, 0x81, 0x8e,
	0x60, 0x5f, 0xb1, 0x94, 0xf1, 0x9a, 0x29, 0xfc, 0xc0, 0x06, 0xff, 0x34, 0x7a, 0x06, 0x61, 0x41,
	0x16, 0x31, 0x29, 0x64, 0x25, 0x0c, 0xde, 0xb2, 0xe9, 0xa0, 0x20, 0x8b, 0x33, 0x6b, 0xbc, 0xed,
	0xfe, 0xf9, 0x7e, 0x0c, 0x46, 0x3f, 0xb6, 0xe0, 0xf0, 0xec, 0xf6, 0xc0, 0x11, 0x4b, 0xa5, 0xa2,
	0xe8, 0x25, 0x3c, 0xb8, 0xb3, 0x47, 0xcc, 0x69, 0xfb, 0xe7, 0xfd, 0x3b, 0xfe, 0x94, 0x22, 0x0c,
	0x7b, 0xba, 0x4a, 0xbe, 0xb2, 0xd4, 0xb4, 0x23, 0x6c, 0x24, 0xf2, 0xe1, 0xc3, 0x42, 0x67, 0xb1,
	0x59, 0x96, 0x2c, 0xae, 0x54, 0xde, 0xce, 0x00, 0x0b, 0x9d, 0x7d, 0x5c, 0x96, 0xec, 0x42, 0xe5,
	0xe8, 0x29, 0x1c, 0x94, 0x32, 0xe7, 0xe9, 0xb2, 0x79, 0xbf, 0xeb, 0x16, 0x70, 0xc6, 0x94, 0xa2,
	0xe7, 0xf0, 0x51, 0x1b, 0xd6, 0x4c, 0x69, 0x2e, 0x05, 0xde, 0xf6, 0x41, 0xd0, 0x8d, 0xf6, 0x9c,
	0xfb, 0xc9, 0x99, 0x68, 0x04, 0xf7, 0xb8, 0xd6, 0x15, 0x53, 0xb1, 0x66, 0xa6, 0x79, 0x67, 0xc7,
	0x52, 0xbb, 0xce, 0x3c, 0x67, 0x66, 0x4a, 0xd1, 0x2b, 0xf8, 0xb8, 0x26, 0x39, 0xa7, 0xf1, 0x17,
	0x25, 0x8b, 0x78, 0xc6, 0x78, 0x36, 0x33, 0xb8, 0xe7, 0x83, 0x60, 0x2b, 0xda, 0xb7, 0xc1, 0x7b,
	0x25, 0x8b, 0x0f, 0xd6, 0x46, 0xaf, 0x21, 0x72, 0x6c, 0x25, 0x0c, 0xcf, 0x37, 0x70, 0xdf, 0xc2,
	0x07, 0x36, 0xb9, 0x68, 0x82, 0x96, 0xc6, 0xb0, 0xa7, 0x58, 0x2d, 0xe7, 0x8c, 0xe2, 0x81, 0x0f,
	0x82, 0x7e, 0xb4, 0x91, 0x28, 0x81, 0x4f, 0x12, 0x22, 0xe6, 0xb1, 0x66, 0x82, 0xc6, 0xe9, 0xcd,
	0x29, 0x31, 0xf4, 0x41, 0xb0, 0x7b, 0x1a, 0x84, 0xf7, 0x74, 0x22, 0xbc, 0xe7, 0xf4, 0x93, 0xee,
	0xd5, 0xaf, 0xe3, 0x4e, 0x34, 0x4c, 0xfe, 0x8f, 0xdc, 0x11, 0x27, 0xa7, 0x57, 0x2b, 0x0f, 0x5c,
	0xaf, 0x3c, 0xf0, 0x7b, 0xe5, 0x81, 0x6f, 0x6b, 0xaf, 0x73, 0xbd, 0xf6, 0x3a, 0x3f, 0xd7, 0x5e,
	0xe7, 0x33, 0x76, 0x05, 0x5d, 0xdc, 0xae, 0x68, 0x73, 0x0e, 0x9d, 0xec, 0xd8, 0xb6, 0xbd, 0xf9,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x14, 0x82, 0x14, 0xb3, 0xc3, 0x02, 0x00, 0x00,
}

func (this *BankSendConstraints) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BankSendConstraints)
	if !ok {
		that2, ok := that.(BankSendConstraints)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.Receiver != that1.Receiver {
		return false
	}
	if this.MaxAmount != that1.MaxAmount {
		return false
	}
	return true
}
func (this *AuthorizationRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AuthorizationRecord)
	if !ok {
		that2, ok := that.(AuthorizationRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AuthorizationId != that1.AuthorizationId {
		return false
	}
	if this.Subject != that1.Subject {
		return false
	}
	if this.MsgTypeUrl != that1.MsgTypeUrl {
		return false
	}
	if this.PolicyId != that1.PolicyId {
		return false
	}
	if this.PolicyVersion != that1.PolicyVersion {
		return false
	}
	if this.IssuerSetId != that1.IssuerSetId {
		return false
	}
	if this.ValidFromHeight != that1.ValidFromHeight {
		return false
	}
	if this.ValidUntilHeight != that1.ValidUntilHeight {
		return false
	}
	if this.Revoked != that1.Revoked {
		return false
	}
	if !this.BankSendConstraints.Equal(&that1.BankSendConstraints) {
		return false
	}
	return true
}
func (m *BankSendConstraints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BankSendConstraints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BankSendConstraints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxAmount) > 0 {
		i -= len(m.MaxAmount)
		copy(dAtA[i:], m.MaxAmount)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.MaxAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuthorizationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BankSendConstraints.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthorization(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.Revoked {
		i--
		if m.Revoked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.ValidUntilHeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ValidUntilHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.ValidFromHeight != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.ValidFromHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x30
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintAuthorization(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuthorizationId) > 0 {
		i -= len(m.AuthorizationId)
		copy(dAtA[i:], m.AuthorizationId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.AuthorizationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthorization(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthorization(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BankSendConstraints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.MaxAmount)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	return n
}

func (m *AuthorizationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuthorizationId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovAuthorization(uint64(m.PolicyVersion))
	}
	if m.IssuerSetId != 0 {
		n += 1 + sovAuthorization(uint64(m.IssuerSetId))
	}
	if m.ValidFromHeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ValidFromHeight))
	}
	if m.ValidUntilHeight != 0 {
		n += 1 + sovAuthorization(uint64(m.ValidUntilHeight))
	}
	if m.Revoked {
		n += 2
	}
	l = m.BankSendConstraints.Size()
	n += 1 + l + sovAuthorization(uint64(l))
	return n
}

func sovAuthorization(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthorization(x uint64) (n int) {
	return sovAuthorization(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BankSendConstraints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BankSendConstraints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BankSendConstraints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthorizationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidFromHeight", wireType)
			}
			m.ValidFromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidFromHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilHeight", wireType)
			}
			m.ValidUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Revoked = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BankSendConstraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BankSendConstraints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthorization(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthorization
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthorization
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthorization
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthorization        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthorization          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthorization = fmt.Errorf("proto: unexpected end of group")
)
