// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alpha/authzattrs/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CurrentIssuerSetSelection selects the current issuer set for one policy scope.
type CurrentIssuerSetSelection struct {
	PolicyId    string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	MsgTypeUrl  string `protobuf:"bytes,2,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	IssuerSetId uint64 `protobuf:"varint,3,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
}

func (m *CurrentIssuerSetSelection) Reset()         { *m = CurrentIssuerSetSelection{} }
func (m *CurrentIssuerSetSelection) String() string { return proto.CompactTextString(m) }
func (*CurrentIssuerSetSelection) ProtoMessage()    {}
func (*CurrentIssuerSetSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba6556b64ca44530, []int{0}
}
func (m *CurrentIssuerSetSelection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentIssuerSetSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentIssuerSetSelection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentIssuerSetSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentIssuerSetSelection.Merge(m, src)
}
func (m *CurrentIssuerSetSelection) XXX_Size() int {
	return m.Size()
}
func (m *CurrentIssuerSetSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentIssuerSetSelection.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentIssuerSetSelection proto.InternalMessageInfo

func (m *CurrentIssuerSetSelection) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *CurrentIssuerSetSelection) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *CurrentIssuerSetSelection) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

// LastAppliedBatchID stores replay state for one issuer set.
type LastAppliedBatchID struct {
	IssuerSetId uint64 `protobuf:"varint,1,opt,name=issuer_set_id,json=issuerSetId,proto3" json:"issuer_set_id,omitempty"`
	BatchId     uint64 `protobuf:"varint,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
}

func (m *LastAppliedBatchID) Reset()         { *m = LastAppliedBatchID{} }
func (m *LastAppliedBatchID) String() string { return proto.CompactTextString(m) }
func (*LastAppliedBatchID) ProtoMessage()    {}
func (*LastAppliedBatchID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba6556b64ca44530, []int{1}
}
func (m *LastAppliedBatchID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LastAppliedBatchID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LastAppliedBatchID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LastAppliedBatchID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastAppliedBatchID.Merge(m, src)
}
func (m *LastAppliedBatchID) XXX_Size() int {
	return m.Size()
}
func (m *LastAppliedBatchID) XXX_DiscardUnknown() {
	xxx_messageInfo_LastAppliedBatchID.DiscardUnknown(m)
}

var xxx_messageInfo_LastAppliedBatchID proto.InternalMessageInfo

func (m *LastAppliedBatchID) GetIssuerSetId() uint64 {
	if m != nil {
		return m.IssuerSetId
	}
	return 0
}

func (m *LastAppliedBatchID) GetBatchId() uint64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

// GenesisState defines the authzattrs module genesis state.
type GenesisState struct {
	Params              Params                      `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Authorizations      []AuthorizationRecord       `protobuf:"bytes,2,rep,name=authorizations,proto3" json:"authorizations"`
	IssuerSets          []IssuerSet                 `protobuf:"bytes,3,rep,name=issuer_sets,json=issuerSets,proto3" json:"issuer_sets"`
	Issuers             []Issuer                    `protobuf:"bytes,4,rep,name=issuers,proto3" json:"issuers"`
	CurrentIssuerSets   []CurrentIssuerSetSelection `protobuf:"bytes,5,rep,name=current_issuer_sets,json=currentIssuerSets,proto3" json:"current_issuer_sets"`
	LastAppliedBatchIds []LastAppliedBatchID        `protobuf:"bytes,6,rep,name=last_applied_batch_ids,json=lastAppliedBatchIds,proto3" json:"last_applied_batch_ids"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba6556b64ca44530, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetAuthorizations() []AuthorizationRecord {
	if m != nil {
		return m.Authorizations
	}
	return nil
}

func (m *GenesisState) GetIssuerSets() []IssuerSet {
	if m != nil {
		return m.IssuerSets
	}
	return nil
}

func (m *GenesisState) GetIssuers() []Issuer {
	if m != nil {
		return m.Issuers
	}
	return nil
}

func (m *GenesisState) GetCurrentIssuerSets() []CurrentIssuerSetSelection {
	if m != nil {
		return m.CurrentIssuerSets
	}
	return nil
}

func (m *GenesisState) GetLastAppliedBatchIds() []LastAppliedBatchID {
	if m != nil {
		return m.LastAppliedBatchIds
	}
	return nil
}

func init() {
	proto.RegisterType((*CurrentIssuerSetSelection)(nil), "alpha.authzattrs.v1.CurrentIssuerSetSelection")
	proto.RegisterType((*LastAppliedBatchID)(nil), "alpha.authzattrs.v1.LastAppliedBatchID")
	proto.RegisterType((*GenesisState)(nil), "alpha.authzattrs.v1.GenesisState")
}

func init() { proto.RegisterFile("alpha/authzattrs/v1/genesis.proto", fileDescriptor_ba6556b64ca44530) }

var fileDescriptor_ba6556b64ca44530 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0xe3, 0x24, 0xa4, 0xcd, 0x4b, 0x41, 0xea, 0x04, 0x21, 0xb7, 0x91, 0x8c, 0xc9, 0xa6,
	0x11, 0x0b, 0x5b, 0x0d, 0x4b, 0x24, 0xa4, 0x06, 0x10, 0xb2, 0xc4, 0x02, 0x39, 0xc0, 0x82, 0x8d,
	0x35, 0xb1, 0x47, 0xce, 0x48, 0x4e, 0xc6, 0x9a, 0x37, 0xae, 0x48, 0x17, 0x9c, 0x81, 0x63, 0xb0,
	0xe4, 0x18, 0x5d, 0x76, 0xc9, 0x0a, 0xa1, 0x64, 0xc1, 0x05, 0x38, 0x00, 0xf2, 0xd8, 0x69, 0x42,
	0x62, 0xba, 0x89, 0x66, 0xe6, 0x7d, 0xdf, 0xef, 0xc5, 0xef, 0x0f, 0x3c, 0xa1, 0x49, 0x3a, 0xa5,
	0x2e, 0xcd, 0xd4, 0xf4, 0x8a, 0x2a, 0x25, 0xd1, 0xbd, 0x3c, 0x77, 0x63, 0x36, 0x67, 0xc8, 0xd1,
	0x49, 0xa5, 0x50, 0x82, 0x74, 0xb5, 0xc4, 0xd9, 0x48, 0x9c, 0xcb, 0xf3, 0x53, 0xbb, 0xca, 0x97,
	0x52, 0x49, 0x67, 0xa5, 0xed, 0xf4, 0xac, 0x4a, 0x91, 0xdf, 0x84, 0xe4, 0x57, 0x54, 0x71, 0x31,
	0x2f, 0x85, 0xc7, 0x74, 0xc6, 0xe7, 0xc2, 0xd5, 0xbf, 0xe5, 0xd3, 0xc3, 0x58, 0xc4, 0x42, 0x1f,
	0xdd, 0xfc, 0x54, 0xbc, 0xf6, 0xbf, 0xc0, 0xc9, 0xcb, 0x4c, 0x4a, 0x36, 0x57, 0x1e, 0x62, 0xc6,
	0xe4, 0x98, 0xa9, 0x31, 0x4b, 0x58, 0x98, 0xb3, 0x48, 0x0f, 0xda, 0xa9, 0x48, 0x78, 0xb8, 0x08,
	0x78, 0x64, 0x1a, 0xb6, 0x31, 0x68, 0xfb, 0x87, 0xc5, 0x83, 0x17, 0x11, 0x1b, 0x8e, 0x66, 0x18,
	0x07, 0x6a, 0x91, 0xb2, 0x20, 0x93, 0x89, 0x59, 0xd7, 0x71, 0x98, 0x61, 0xfc, 0x7e, 0x91, 0xb2,
	0x0f, 0x32, 0x21, 0x7d, 0xb8, 0xcf, 0x35, 0x34, 0x40, 0xa6, 0x72, 0x44, 0xc3, 0x36, 0x06, 0x4d,
	0xbf, 0xc3, 0xd7, 0x99, 0xbc, 0xa8, 0x3f, 0x06, 0xf2, 0x96, 0xa2, 0xba, 0x48, 0xd3, 0x84, 0xb3,
	0x68, 0x44, 0x55, 0x38, 0xf5, 0x5e, 0xed, 0x3b, 0x8d, 0x3d, 0x27, 0x39, 0x81, 0xc3, 0x49, 0x2e,
	0xcf, 0xc3, 0x75, 0x1d, 0x3e, 0xd0, 0x77, 0x2f, 0xea, 0xff, 0x69, 0xc0, 0xd1, 0x9b, 0xa2, 0xde,
	0x63, 0x45, 0x15, 0x23, 0x2f, 0xa0, 0x55, 0xd4, 0x51, 0x83, 0x3a, 0xc3, 0x9e, 0x53, 0x51, 0x7f,
	0xe7, 0x9d, 0x96, 0x8c, 0xda, 0xd7, 0x3f, 0x1f, 0xd7, 0xbe, 0xfd, 0xfe, 0xfe, 0xd4, 0xf0, 0x4b,
	0x17, 0xf9, 0x08, 0x0f, 0xfe, 0xa9, 0x32, 0x9a, 0x75, 0xbb, 0x31, 0xe8, 0x0c, 0x07, 0x95, 0x9c,
	0x8b, 0x6d, 0xa9, 0xcf, 0x42, 0x21, 0xa3, 0x51, 0x33, 0x87, 0xfa, 0x3b, 0x14, 0xf2, 0x1a, 0x3a,
	0x9b, 0xef, 0x44, 0xb3, 0xa1, 0xa1, 0x56, 0x25, 0xf4, 0xb6, 0x3d, 0x25, 0x0a, 0x6e, 0x6b, 0x81,
	0xe4, 0x39, 0x1c, 0x14, 0x37, 0x34, 0x9b, 0x1a, 0xd1, 0xbb, 0x03, 0x51, 0xfa, 0xd7, 0x0e, 0x12,
	0x41, 0x37, 0x2c, 0x26, 0x20, 0xd8, 0xfe, 0x2f, 0xf7, 0x34, 0xc8, 0xa9, 0x04, 0xfd, 0x77, 0x62,
	0x4a, 0xf6, 0x71, 0xb8, 0x23, 0x40, 0x32, 0x81, 0x47, 0x09, 0x45, 0x15, 0xd0, 0xa2, 0xd1, 0xc1,
	0xba, 0x75, 0x68, 0xb6, 0x74, 0xa2, 0xb3, 0xca, 0x44, 0xfb, 0xa3, 0x51, 0x66, 0xe8, 0x26, 0xbb,
	0x91, 0x08, 0x47, 0xc3, 0xeb, 0xa5, 0x65, 0xdc, 0x2c, 0x2d, 0xe3, 0xd7, 0xd2, 0x32, 0xbe, 0xae,
	0xac, 0xda, 0xcd, 0xca, 0xaa, 0xfd, 0x58, 0x59, 0xb5, 0x4f, 0x66, 0xb1, 0x37, 0x9f, 0xb7, 0x37,
	0x27, 0x1f, 0x5c, 0x9c, 0xb4, 0xf4, 0x1a, 0x3c, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xce,
	0xff, 0xd0, 0xb4, 0x03, 0x00, 0x00,
}

func (m *CurrentIssuerSetSelection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentIssuerSetSelection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentIssuerSetSelection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IssuerSetId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LastAppliedBatchID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LastAppliedBatchID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LastAppliedBatchID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BatchId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BatchId))
		i--
		dAtA[i] = 0x10
	}
	if m.IssuerSetId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.IssuerSetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastAppliedBatchIds) > 0 {
		for iNdEx := len(m.LastAppliedBatchIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastAppliedBatchIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.CurrentIssuerSets) > 0 {
		for iNdEx := len(m.CurrentIssuerSets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurrentIssuerSets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Issuers) > 0 {
		for iNdEx := len(m.Issuers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Issuers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.IssuerSets) > 0 {
		for iNdEx := len(m.IssuerSets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.IssuerSets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Authorizations) > 0 {
		for iNdEx := len(m.Authorizations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Authorizations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CurrentIssuerSetSelection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.IssuerSetId != 0 {
		n += 1 + sovGenesis(uint64(m.IssuerSetId))
	}
	return n
}

func (m *LastAppliedBatchID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IssuerSetId != 0 {
		n += 1 + sovGenesis(uint64(m.IssuerSetId))
	}
	if m.BatchId != 0 {
		n += 1 + sovGenesis(uint64(m.BatchId))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Authorizations) > 0 {
		for _, e := range m.Authorizations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.IssuerSets) > 0 {
		for _, e := range m.IssuerSets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Issuers) > 0 {
		for _, e := range m.Issuers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CurrentIssuerSets) > 0 {
		for _, e := range m.CurrentIssuerSets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LastAppliedBatchIds) > 0 {
		for _, e := range m.LastAppliedBatchIds {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CurrentIssuerSetSelection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentIssuerSetSelection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentIssuerSetSelection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LastAppliedBatchID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LastAppliedBatchID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LastAppliedBatchID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSetId", wireType)
			}
			m.IssuerSetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerSetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchId", wireType)
			}
			m.BatchId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authorizations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authorizations = append(m.Authorizations, AuthorizationRecord{})
			if err := m.Authorizations[len(m.Authorizations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerSets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerSets = append(m.IssuerSets, IssuerSet{})
			if err := m.IssuerSets[len(m.IssuerSets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuers = append(m.Issuers, Issuer{})
			if err := m.Issuers[len(m.Issuers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentIssuerSets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentIssuerSets = append(m.CurrentIssuerSets, CurrentIssuerSetSelection{})
			if err := m.CurrentIssuerSets[len(m.CurrentIssuerSets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAppliedBatchIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastAppliedBatchIds = append(m.LastAppliedBatchIds, LastAppliedBatchID{})
			if err := m.LastAppliedBatchIds[len(m.LastAppliedBatchIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
